[package]
name = "sbc8micro"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version="1.0.219", features = ["derive"]}
serde_json = "1.0.140"
ratatui = "0.29"
crossterm = "0.29"
log = "0.4.27"
simple-logging = "2.0.2"
bitflags = "2.9.1"
